### ISSUE TITLE
Webpack Import Failing

### ISSUE THREAD

**Issue by KamesCG** [dethertech/dether.js#24]
Quickly grabbed snippet from documentation -https://dethertech.github.io/dether.js/class/src/detherUser.js~DetherUser.html

```
import DetherUser from 'detherjs/src/detherUser.js'
```

**Failing**
```
import DetherJS from 'detherjs/detherJs.js'
import DetherUser from 'detherjs/detherUser.js'
import DetherJS from 'detherjs/src/detherJs.js'
import DetherUser from 'detherjs/src/detherUser.js'

Module not found: Can't resolve 'detherjs/detherUser'
```

**Working**
```import DetherJS from 'detherjs'```

**Comment by pakokrew** [comment]
hi,

The import example in the doc link is invalid
You should always include just the default package only.

Furthermore, the DetherUser is not meant to be manually instanciated, but rather from DetherJs.getUser

**Comment by KamesCG** [comment]
I see :) I knew it felt it weird.

I'll have to fully dig into the docs.

**Comment by KamesCG** [comment]
Of course :) I knew it felt a little weird.

I'm just porting over to Redux/Saga flow and was blindly just copying/pasting imports and methds

https://github.com/EidenaiEth/Dether-Redux-Department

**Comment by pakokrew** [comment]
@Fukunaga42 We have to remove the import example in the esdoc

**Comment by Fukunaga42** [comment]
We change the doc, I close
